identity:
    orgId: sloues
    typeId: test
    deviceId: device1
    appId: mqtt
auth:
    # key: I dont know where to get this
    token: &gq7)2zFTMGwJ!YPnL
options:
    domain: internetofthings.ibmcloud.com
    logLevel: debug
    http:
        verify: True
    mqtt:
        instanceId: instance1
        port: 1883
        transport: tcp
        cleanStart: true
        sessionExpiry: 7200
        keepAlive: 60
