identity:
    orgId: sloues
    typeId: test
    deviceId: device1
    appId: mqtt
auth:
    key: a-sloues-ytv8pacw0b
    token: B2ac0MWCw0r6xdcOQ2
    # token: 6hlEXwFDMfEN&RIm@r
options:
    domain: internetofthings.ibmcloud.com
    logLevel: debug
    mqtt:
        instanceId: instance1
        port: 1883
        transport: tcp
        cleanStart: true
        sessionExpiry: 7200
        keepAlive: 60
    # http:
    #     verify: True
