identity:
    appId: mqtt
auth:
    key: a-sloues-jxmmyvgorh
    token: 7T1zlo9WchAdqk6xzb
options:
    domain: internetofthings.ibmcloud.com
    logLevel: debug
    mqtt:
        instanceId: instance1
        port: 1883
        transport: tcp
        cleanStart: true
        sessionExpiry: 7200
        keepAlive: 60
